name: AoC 2015

on:
  push:
    paths:
    - 'advent-of-code-2015/'

defaults:
  run:
    working-directory: advent-of-code-201

env:
  CARGO_TERM_COLOR: always

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - run: cargo build

      - run: cargo test

      - run: cargo run --release
